---
- hosts: localhost
  gather_facts: no
  vars:
    vcenter_server: "10.9.70.193"
    vcenter_user: "administrator@vsphere.local"
    vcenter_pass: "Anthos#123"
    datacenter_name: "SysPoC"
    cluster_name: "ansiblePoC_cluster"
  tasks:
  - name: Power off vm
    vmware_guest:
      hostname: "{{ vcenter_server }}"
      username: "{{ vcenter_user }}"
      password: "{{ vcenter_pass }}"
      validate_certs: False
      name: poc_linux_vm
      template: "redhat-temp8.4"
      datacenter: "{{ datacenter_name }}"
      folder: /{{ datacenter_name }}/vm
      cluster: "{{ cluster_name }}"
      datastore: "datastore1_anthos_esxi0"
      state: powered-off

  - name: Delete the template
    vmware_guest:
      hostname: "{{ vcenter_server }}"
      username: "{{ vcenter_user }}"
      password: "{{ vcenter_pass }}"
      validate_certs: False
      name: poc_linux_vm
      template: "redhat-temp8.4"
      datacenter: "{{ datacenter_name }}"
      folder: /{{ datacenter_name }}/vm
      cluster: "{{ cluster_name }}"
      datastore: "datastore1_anthos_esxi0"
      state: absent

