---
- hosts: localhost
  gather_facts: no
  vars:
    vcenter_server: "10.0.55.12"
    vcenter_user: "software@vsphere.local"
    vcenter_pass: "Qaz123$%^;"
    datacenter_name: "Amigo"
    cluster_name: "AMIGO LAB"
  tasks:
  - name: Power off vm
    vmware_guest:
      hostname: "{{ vcenter_server }}"
      username: "{{ vcenter_user }}"
      password: "{{ vcenter_pass }}"
      validate_certs: False
      name: poc_win_vm
      template: win10_template
      resource_pool: "Software"
      datacenter: "{{ datacenter_name }}"
      folder: /{{ datacenter_name }}/vm
      cluster: "{{ cluster_name }}"
      datastore: "AMIGO LAB"
      state: powered-off

  - name: Delete the template
    vmware_guest:
      hostname: "{{ vcenter_server }}"
      username: "{{ vcenter_user }}"
      password: "{{ vcenter_pass }}"
      validate_certs: False
      name: poc_win_vm
      template: win10_template
      resource_pool: "Software"
      datacenter: "{{ datacenter_name }}"
      folder: /{{ datacenter_name }}/vm
      cluster: "{{ cluster_name }}"
      datastore: "AMIGO LAB"
      state: absent
