---
- hosts: localhost
  gather_facts: no
  vars:
    vcenter_server: "10.0.55.12"
    vcenter_user: "software@vsphere.local"
    vcenter_pass: "Qaz123$%^;"
    datacenter_name: "Amigo"
    cluster_name: "AMIGO LAB"
  tasks:
  - name: Clone the template
    vmware_guest:
      hostname: "{{ vcenter_server }}"
      username: "{{ vcenter_user }}"
      password: "{{ vcenter_pass }}"
      validate_certs: False
      name: poc_win_vm
      template: win10_template
      resource_pool: "Software"
      datacenter: "{{ datacenter_name }}"
      folder: /{{ datacenter_name }}/vm
      cluster: "{{ cluster_name }}"
      datastore: "AMIGO LAB"
      state: poweredon
      networks:
        - name: "PG-VLAN155"
          connected: yes
          ip: 10.0.55.194
          netmask: 255.255.255.0
          gateway: 10.0.55.1
          dns_servers: 8.8.8.8
          wait_for_ip_address: True


